# REST API

### Get All Profile
GET http://localhost:3000/profile
### Create New Profile
### curl -X POST http://localhost:3000/profile
POST http://localhost:3000/profile
Content-Type: application/json

{
  "username":"1234",  
  "password":"KKaa.123456",
  "mobile":"0225576289",     
  "cardId":"1600801888727" 
      
}